FROM php:7-fpm-alpine3.6
MAINTAINER https://github.com/surenkid/

RUN docker-php-ext-install pdo pdo_mysql

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS \
      && pecl install redis \
      && pecl install xdebug \
      && docker-php-ext-enable redis xdebug \
      && apk del .build-deps